Update docs via Travis
Last commit message:
PetrifyNotFoundException: Use a cause for the execption

Build URL: https://travis-ci.org/CvO-Theory/apt/builds/254349325